Repository Bori-Bori/client, pull requests merged in 2022-10, with the labels that each got.

#1 [Feature] a기능, b기능 수행
  src/aa.js
  src/bbb.js
Labels: enhancement

#9 fix: main에서 develop으로의 머지 요청
  .eslintrc
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Light.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/icons/bookmark-default-24.png
  src/assets/icons/bookmark-select-24.png
  src/assets/icons/close-bk-16.png
  src/assets/icons/close-bk-24.png
  src/assets/icons/comment-gr-16.png
  src/assets/icons/comment-gr-60.png
  src/assets/icons/comment-wh-24.png
  src/assets/icons/down-bk-12.png
  src/assets/icons/down-bk-16.png
  src/assets/icons/down-bk-24.png
  src/assets/icons/down-gr-12.png
  src/assets/icons/logo-horizon-26.png
  src/assets/icons/logo-horizon-54.png
  src/assets/icons/logo-square.png
  src/assets/icons/nxt-bk-20.png
  src/assets/icons/nxt-gr-20.png
  src/assets/icons/prv-bk-20.png
  src/assets/icons/prv-gr-20.png
  src/assets/icons/search-bk-24.png
  src/assets/icons/search-yl-16.png
  src/assets/icons/search-yl-20.png
  src/assets/icons/up-bk-24.png
  src/assets/icons/user-gr-16.png
  src/assets/icons/user-wh-24.png
  src/assets/icons/user-yl-20.png
  src/index.css
  src/index.tsx
  src/pages/Home.tsx
  src/router/Router.tsx
  src/styles/GlobalStyle.tsx
  src/styles/Theme.tsx
  src/styles/font.css
  src/types/book.ts
  tsconfig.json
Labels: Type: Bug

#11 상세페이지(Detail) UI 구현
  src/App.tsx
  src/components/1.txt
  src/components/CommonButton.tsx
  src/pages/1.txt
  src/pages/Detail/components/BookInfo.tsx
  src/pages/Detail/components/BubbleBox.tsx
  src/pages/Detail/components/Comment.tsx
  src/pages/Detail/components/CommentItem.tsx
  src/pages/Detail/components/InputComment.tsx
  src/pages/Detail/components/InputCommentWithPage.tsx
  src/pages/Detail/components/SlideButton.tsx
  src/pages/Detail/components/SlideRange.tsx
  src/pages/Detail/components/ToggleButton.tsx
  src/pages/Detail/index.tsx
  src/pages/Home.tsx
  src/styles/GlobalStyle.tsx
  src/types/book.ts
Labels: Type: Feature, Status: In Progress

#13 #12 feat: slide UI 추가
  src/assets/icons/bookmark-default-24.png
  src/assets/icons/bookmark-select-24.png
  src/assets/icons/common_comment_gr_24.png
  src/assets/icons/common_user_gr_24.png
  src/assets/slide/book01.png
  src/assets/slide/book02.png
  src/assets/slide/book03.png
  src/assets/slide/book04.png
  src/assets/slide/book05.png
  src/assets/slide/book06.png
  src/assets/slide/book07.png
  src/assets/slide/book08.png
  src/assets/slide/book09.png
  src/assets/slide/book10.png
  src/pages/Home.tsx
  src/pages/Main/components/Slide.tsx
  src/pages/Main/components/bookData.ts
  src/pages/Main/index.tsx
  src/router/Router.tsx
  src/styles/GlobalStyle.tsx
  src/types/book.ts
Labels: Type: Feature
