Repository Bori-Bori/client, pull requests merged in 2023-02, with the labels that each got.

#41 feat: 알람기능 추가, home 페이지 css 수정
  package-lock.json
  package.json
  src/apis/notification.ts
  src/assets/icons/common_alarm_triangle.png
  src/assets/icons/common_bell_yl_24.png
  src/components/header/Header.tsx
  src/components/header/NotificationBox.tsx
  src/components/header/NotificationItem.tsx
  src/components/header/NotificationList.tsx
  src/components/header/Search.tsx
  src/pages/Detail/index.tsx
  src/router/Router.tsx
Labels: Type: Feature, Type: Improvement, Status: Done

#43 feat: home 페이지 css 수정
  src/components/header/Icons.tsx
  src/components/header/NotificationList.tsx
  src/pages/Detail/components/BookInfo.tsx
  src/pages/Detail/components/Comment.tsx
  src/pages/Detail/components/CommentContainer.tsx
  src/pages/Detail/components/CommentItem.tsx
  src/pages/Detail/components/InputComment.tsx
  src/pages/Detail/components/ReplyComments.tsx
  src/pages/Detail/components/ReplyPagination.tsx
  src/pages/Detail/components/SlideRange.tsx
  src/pages/Detail/components/ToggleButton.tsx
  src/pages/Detail/components/ToggleInputComment.tsx
  src/pages/Detail/index.tsx
  src/styles/Theme.tsx
Labels: Type: Improvement, Status: Done

#51 #49 fix: input range slide 말풍선 위치 문제 최종 해결
  src/pages/Detail/components/sorting/SlideRange.tsx
Labels: Type: Bug, Status: Done

#53 feat: 로그인 state 전역관리 및 프로필 수정 시 UI 가 정상적으로 바뀌지 않는 버그 수정
  src/components/header/Icons.tsx
  src/hooks/useIsLogin.ts
  src/pages/Detail/components/comment/CommentContainer.tsx
  src/pages/Detail/components/comment/InputCommentWithPage.tsx
  src/pages/Detail/components/comment/ToggleInputComment.tsx
  src/pages/Detail/components/comment/ToggleInputCommentMoblie.tsx
  src/pages/Detail/components/reply/ReplyComments.tsx
  src/pages/Detail/index.tsx
  src/pages/Login/KakaoLogin/index.tsx
  src/pages/Mypage/components/EditProfileModal.tsx
  src/pages/Mypage/components/Profile.tsx
  src/recoil/profile.ts
Labels: Type: Improvement, Status: Done
